# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# SEO
title: d9beuD's Blog
email: v.bathelier@d9beud.com
description: >- 
  A blog about web development, programming, and other tech-related topics. I want
  to share my knowledge and experience with the community. I will mainly write
  about PHP, Symfony, Vue.js, Jekyll, Api Platform, and other technologies I use.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  d9beuD

author:
  name: Vincent BATHELIER
  url: https://d9beud.com

timezone: Europe/Paris

# Build settings
plugins:
  - jekyll-feed

postcss:
  cache: false

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

pagination:
  enabled: true
  per_page: 10
  permalink: /:num.html
  title: ':title (:num of :max)'
  limit: 0
  trail:
    before: 2
    after: 2
  collection: posts
  sort_reverse: true

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      author: 
        name: Vincent BATHELIER
        avatar: /assets/img/vbathelier.webp
        bio: >-
          I am a web developer and I love to share my knowledge with the community.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
